import { test } from 'node:test';
import assert from 'node:assert/strict';
import {
  IMAGE_NO_TEXT_RULE,
  buildGroundedVisualPrompt,
  isGenericMediaPrompt,
  resolveVisualSubject,
} from './imageVisualPrompt.ts';

const polymerCourse = 'Polymers: PE and PP Chemistry';

test('EVA in a polymer course is plastic resin, not an astronaut', () => {
  const { visual, forbid } = resolveVisualSubject({
    courseTitle: polymerCourse,
    slideTitle: 'Polyethylene Types and Densities',
    panelLabel: 'EVA',
    panelBody: 'Ethylene-vinyl acetate copolymer. Density 0.920-0.945 g/cm3. Vinyl acetate comonomer added.',
  });
  assert.match(visual, /ethylene-vinyl acetate|copolymer|resin|film/i);
  assert.doesNotMatch(visual, /\bastronaut/i);
  assert.ok(forbid.some((f) => /astronaut/i.test(f)));

  const { prompt, intended } = buildGroundedVisualPrompt({
    courseTitle: polymerCourse,
    slideTitle: 'Polyethylene Types and Densities',
    panelLabel: 'EVA',
    panelBody: 'Ethylene-vinyl acetate copolymer. Density 0.920-0.945 g/cm3.',
  });
  assert.match(prompt, /HARD RULE: The image must contain absolutely no text/i);
  assert.match(prompt, /ethylene-vinyl acetate/i);
  assert.doesNotMatch(prompt, /\bastronaut/i);
  assert.match(intended, /astronaut/i);
  assert.match(intended, /no readable text/i);
  assert.doesNotMatch(prompt, /Simple clear educational photo or illustration of: EVA\./);
});

test('Termination in radical polymerization is chain chemistry, not a job firing', () => {
  const { visual, forbid } = resolveVisualSubject({
    courseTitle: polymerCourse,
    moduleTitle: 'Polymer Fundamentals',
    slideTitle: 'Radical Polymerization: Three Steps',
    panelLabel: 'Termination',
    panelBody: 'Two active radicals collide and combine. Unpaired electrons pair up, stopping growth.',
  });
  assert.match(visual, /polymer-chain termination|radical|chain ends/i);
  assert.doesNotMatch(visual, /firing|layoff|pink slip/i);
  assert.ok(forbid.some((f) => /firing|layoff/i.test(f)));

  const { prompt, intended } = buildGroundedVisualPrompt({
    courseTitle: polymerCourse,
    slideTitle: 'Radical Polymerization: Three Steps',
    panelLabel: 'Termination',
    panelBody: 'Two active radicals collide and combine.',
  });
  assert.match(prompt, /Do not show people/i);
  assert.doesNotMatch(prompt, /job firing|layoff/i);
  assert.match(intended, /firing|layoff/i);
});

test('Initiation in radical polymerization is not a handshake', () => {
  const { visual, forbid } = resolveVisualSubject({
    courseTitle: polymerCourse,
    slideTitle: 'Radical Polymerization: Three Steps',
    panelLabel: 'Initiation',
    panelBody: 'Free radicals generated by heat or catalyst. Radicals attack monomer double bonds.',
  });
  assert.match(visual, /initiation|radical|catalyst|monomer/i);
  assert.ok(forbid.some((f) => /handshake/i.test(f)));
});

test('prompts always carry the no-text rule and never ask to typeset titles', () => {
  const { prompt } = buildGroundedVisualPrompt({
    courseTitle: polymerCourse,
    slideTitle: 'Polyethylene Types and Densities',
    panelLabel: 'INTRODUCTION',
    panelBody: 'Four main PE types exist. Each has a distinct density range. Density drives end-use application.',
  });
  assert.match(prompt, new RegExp(IMAGE_NO_TEXT_RULE.slice(0, 40)));
  assert.match(prompt, /never typeset|unlabeled|no text/i);
  assert.doesNotMatch(prompt, /typeset the course title onto the image/i);
});

test('generic mediaPrompt fallbacks are ignored in favor of panel body', () => {
  assert.equal(isGenericMediaPrompt('Professional illustration related to EVA'), true);
  const { visual } = resolveVisualSubject({
    courseTitle: polymerCourse,
    slideTitle: 'Monomers, Comonomers, and Catalysts',
    panelLabel: 'Monomer',
    panelBody: 'Small molecule that repeats in a polymer. Example: ethylene (C2H4) for polyethylene.',
    mediaPrompt: 'Professional illustration related to Monomer',
  });
  assert.match(visual, /monomer|laboratory bottle|feedstock/i);
  assert.doesNotMatch(visual, /^Professional illustration related to/i);
});
