/**
 * stripe_setup.mjs
 * ─────────────────────────────────────────────────────────────────────────────
 * One-time script to create all NexCourse AI products & prices in Stripe.
 * Run ONCE with: node stripe_setup.mjs <YOUR_STRIPE_SECRET_KEY>
 *
 * What it creates:
 *   Subscriptions:
 *     - Creator (Annual)             $708 / year  ($59/mo equivalent)
 *     - Creator (Monthly)            $79 / month
 *     - Team (Annual)                $1,788 / year ($149/mo · up to 5 seats)
 *
 *   One-time credit packs:
 *     - Standard Credit Pack         $25
 *     - Volume Credit Pack          $100
 *
 * Output: Appends all Price IDs to your .env file automatically.
 * Prefer stripe_create_v2_prices.mjs when migrating an existing Stripe account.
 * ─────────────────────────────────────────────────────────────────────────────
 */

import Stripe from 'stripe';
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const secretKey = process.argv[2];
if (!secretKey || !secretKey.startsWith('sk_')) {
  console.error('\n❌  Usage: node stripe_setup.mjs <YOUR_STRIPE_SECRET_KEY>');
  console.error('   Example: node stripe_setup.mjs sk_test_51abc...\n');
  process.exit(1);
}

const stripe = new Stripe(secretKey, { apiVersion: '2024-12-18.acacia' });

const PRODUCTS = [
  {
    envKey:      'STRIPE_PRICE_PRO_CREATOR_ANNUAL',
    name:        'Creator (Annual)',
    description: '500 AI + 500 TTS credits/mo · Alloy voice · 3 cloud drafts · SCORM export · $59/mo billed annually',
    metadata:    { track: 'corporate', tier: 'pro_creator', billing: 'annual', credits_monthly: '500' },
    price:       70800,
    currency:    'usd',
    type:        'recurring',
    interval:    'year',
  },
  {
    envKey:      'STRIPE_PRICE_PRO_CREATOR_MONTHLY',
    name:        'Creator (Monthly)',
    description: '500 AI + 500 TTS credits/mo · Alloy voice · 3 cloud drafts · SCORM export · $79/mo billed monthly',
    metadata:    { track: 'corporate', tier: 'pro_creator', billing: 'monthly', credits_monthly: '500' },
    price:       7900,
    currency:    'usd',
    type:        'recurring',
    interval:    'month',
  },
  {
    envKey:      'STRIPE_PRICE_BUSINESS_TEAM_ANNUAL',
    name:        'Team (Annual)',
    description: '1,500 pooled credits/mo · up to 5 seats · 10 shared drafts · all 6 TTS voices · $149/mo billed annually',
    metadata:    { track: 'corporate', tier: 'business_team', billing: 'annual', credits_monthly: '1500', seats: '5' },
    price:       178800,
    currency:    'usd',
    type:        'recurring',
    interval:    'year',
  },
  {
    envKey:      'STRIPE_PRICE_CREDITS_STANDARD',
    name:        'Standard Credit Pack',
    description: '100 AI credits · Never expire · Stack on top of subscription',
    metadata:    { type: 'credit_pack', credits: '100' },
    price:       2500,
    currency:    'usd',
    type:        'one_time',
  },
  {
    envKey:      'STRIPE_PRICE_CREDITS_VOLUME',
    name:        'Volume Credit Pack',
    description: '500 AI credits · Best value (save 20%) · Never expire · Stack on top of subscription',
    metadata:    { type: 'credit_pack', credits: '500' },
    price:       10000,
    currency:    'usd',
    type:        'one_time',
  },
];

function formatPrice(cents) {
  return `$${(cents / 100).toFixed(2)}`;
}

async function createProductAndPrice(def) {
  const product = await stripe.products.create({
    name:        def.name,
    description: def.description,
    metadata:    def.metadata ?? {},
  });
  console.log(`  ✅  Product created: ${product.name} (${product.id})`);

  const priceData = {
    product:     product.id,
    unit_amount: def.price,
    currency:    def.currency,
    metadata:    def.metadata ?? {},
  };

  if (def.type === 'recurring') {
    priceData.recurring = { interval: def.interval };
  }

  const price = await stripe.prices.create(priceData);
  const label = def.type === 'recurring'
    ? `${formatPrice(def.price)}/${def.interval}`
    : `${formatPrice(def.price)} one-time`;
  console.log(`  ✅  Price created:   ${label} → ${price.id}`);

  return { envKey: def.envKey, priceId: price.id, name: def.name };
}

async function main() {
  console.log('\n🚀  NexCourse AI — Stripe Product Setup (v2)');
  console.log('━'.repeat(55));

  const results = [];

  for (const def of PRODUCTS) {
    console.log(`\n→ Creating: ${def.name}`);
    try {
      const result = await createProductAndPrice(def);
      results.push(result);
    } catch (err) {
      console.error(`  ❌  Failed for ${def.name}: ${err.message}`);
      process.exit(1);
    }
  }

  console.log('\n' + '━'.repeat(55));
  console.log('📋  All Price IDs:\n');
  for (const r of results) {
    console.log(`  ${r.envKey}=${r.priceId}`);
  }

  const __dirname = path.dirname(fileURLToPath(import.meta.url));
  const envPath   = path.join(__dirname, '.env');

  const envBlock = [
    '',
    '# ── Stripe Price IDs (auto-generated by stripe_setup.mjs v2) ─────────────',
    ...results.map(r => `${r.envKey}=${r.priceId}`),
    // Legacy aliases used as fallbacks in server.js
    `STRIPE_PRICE_PRO_CREATOR=${results.find(r => r.envKey === 'STRIPE_PRICE_PRO_CREATOR_ANNUAL')?.priceId ?? ''}`,
    `STRIPE_PRICE_BUSINESS_TEAM=${results.find(r => r.envKey === 'STRIPE_PRICE_BUSINESS_TEAM_ANNUAL')?.priceId ?? ''}`,
    '',
  ].join('\n');

  fs.appendFileSync(envPath, envBlock, 'utf8');

  console.log('\n✅  Price IDs appended to .env successfully!');
  console.log('\n⚠️   Also set the new STRIPE_PRICE_* keys on Render (production server).');
  console.log('\n🎉  Stripe setup complete!\n');
}

main().catch(err => {
  console.error('\n❌  Unexpected error:', err.message);
  process.exit(1);
});
